### PR TITLE
Use full paths for relationships

### PR DESCRIPTION
**Pull request by adkron**

### CODE REVIEW

**Comment by adkron** [comment]
I don't think this will pass until we put out a new version of package.

**Comment by adkron** [comment]
My last commit message is wrong. I can force push a change if we like.

**Comment by boblail** [comment]
Amos, do you need to pull changes on `master` locally in `openxml-package`? Maybe then a `bundle update openxml-package` will do it?

**Comment by adkron** [comment]
Thanks, @boblail. I think that did it.

**Comment by adkron** [comment]
🤞

**Comment by adkron** [comment]
:100:

**Review by boblail — APPROVED** [review]

**Pull request merged**
